#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


case "$1" in
  configure)
    
	if ! omv_config_exists "/config/services/bintray"; then
      echo "Initialize configuration"
      omv_config_add_element "/config/services" "bintray"
      omv_config_add_element "/config/services/bintray" "username" ""
      omv_config_add_element "/config/services/bintray" "apikey" ""
      omv_config_add_element "/config/services/bintray" "gpgpass" ""
    fi

    if ! omv_config_exists "/config/services/bintray/packages"; then
        omv_config_add_element "/config/services/bintray" "packages" ""
    fi

    dpkg-trigger update-fixperms
    dpkg-trigger update-locale

    ;;

abort-upgrade|abort-remove|abort-deconfigure)
    ;;

*)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
